# Generated by Django 3.1.7 on 2022-06-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtmodel',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='time',
        ),
    ]
