# Generated by Django 3.1.7 on 2022-06-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220615_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DTModel',
            new_name='Booking',
        ),
    ]
